import type { Trial } from "./types";

export const TRIALS: Trial[] = [
  {
    id: "horizon",
    nctId: "NCT04023552",
    name: "HORIZON",
    agent: "Pelacarsen (TQJ230)",
    sponsor: "Novartis Pharmaceuticals",
    company: "Novartis / Ionis",
    mechanism: "LPA ASO",
    dose: "80 mg SC monthly",
    population:
      "Established CVD. Secondary prevention in patients with elevated Lp(a).",
    biomarkerThreshold: "≥70 mg/dL; planned analysis at ≥90 mg/dL",
    enrollment: 8323,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time to first CEC-confirmed expanded MACE (cardiovascular death, non-fatal MI, non-fatal stroke, and urgent coronary revascularization requiring hospitalization) in patients with Lp(a) ≥70 mg/dL; co-primary in patients with Lp(a) ≥90 mg/dL.",
    startDate: "2019-12-12",
    primaryCompletion: "2026-07-16",
    status: "Completed",
    prevention: "secondary",
    keyDifference:
      "Failed reference. CT.gov lists Completed (primary completion 16 Jul 2026).",
    failedReference: true,
    lpLoweringPct: 77,
  },
  {
    id: "ocean-outcomes",
    nctId: "NCT05581303",
    name: "OCEAN(a)-Outcomes",
    agent: "Olpasiran",
    sponsor: "Amgen",
    company: "Amgen",
    mechanism: "LPA siRNA",
    dose: "SC every 12 weeks",
    population:
      "Age 18–85 with ASCVD (prior MI and/or PCI plus ≥1 additional risk factor).",
    biomarkerThreshold: "≥200 nmol/L",
    enrollment: 7297,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time to CHD death, myocardial infarction, or urgent coronary revascularization, whichever occurs first.",
    startDate: "2022-12-14",
    primaryCompletion: "2028-03-31",
    status: "Active, not recruiting",
    prevention: "secondary",
    keyDifference:
      "Coronary-focused population and endpoint. Stroke is not in the primary composite.",
    lpLoweringPct: 101.1,
  },
  {
    id: "ocean-prevent",
    nctId: "NCT07136012",
    name: "OCEAN(a)-PreEvent",
    agent: "Olpasiran",
    sponsor: "Amgen",
    company: "Amgen",
    mechanism: "LPA siRNA",
    dose: "SC every 12 weeks",
    population:
      "Age ≥50 with multiple ASCVD risk factors and/or atherosclerosis. No prior acute atherothrombotic event or arterial revascularization.",
    biomarkerThreshold: "≥200 nmol/L",
    enrollment: 11000,
    enrollmentType: "estimated",
    primaryEndpoint:
      "Time to CHD death, myocardial infarction, or urgent coronary revascularization, whichever occurs first.",
    startDate: "2025-08-22",
    primaryCompletion: "2031-10-20",
    status: "Recruiting",
    prevention: "primary",
    keyDifference: "First-event prevention. Same coronary-focused endpoint as Outcomes.",
    lpLoweringPct: 101.1,
  },
  {
    id: "acclaim",
    nctId: "NCT06292013",
    name: "ACCLAIM-Lp(a)",
    agent: "Lepodisiran",
    sponsor: "Eli Lilly and Company",
    company: "Lilly",
    mechanism: "LPA siRNA",
    dose: "SC; 400 mg every 6 months in prior trials",
    population:
      "Lp(a) elevated plus established ASCVD, or age ≥55 at risk for a first CV event.",
    biomarkerThreshold: "≥175 nmol/L",
    enrollment: 17300,
    enrollmentType: "estimated",
    primaryEndpoint:
      "Time to first event in a MACE-4 composite of cardiovascular death, nonfatal myocardial infarction, nonfatal ischemic stroke, and urgent coronary revascularization.",
    startDate: "2024-03-05",
    primaryCompletion: "2029-03",
    status: "Active, not recruiting",
    prevention: "mixed",
    keyDifference: "Largest Lp(a) outcomes trial. Includes first-event prevention.",
    lpLoweringPct: 93.9,
  },
  {
    id: "move",
    nctId: "NCT07157774",
    name: "MOVE-Lp(a)",
    agent: "Muvalaplin",
    sponsor: "Eli Lilly and Company",
    company: "Lilly",
    mechanism: "Lp(a) assembly inhibitor",
    dose: "Oral; 120 mg daily in prior trials",
    population:
      "Prior ASCVD event within 10 years, or at risk for a first ASCVD event.",
    biomarkerThreshold: "≥175 nmol/L",
    enrollment: 10450,
    enrollmentType: "estimated",
    primaryEndpoint:
      "Time to first event in a MACE-4 composite of cardiovascular death, nonfatal myocardial infarction, nonfatal ischemic stroke, and urgent coronary revascularization.",
    startDate: "2025-09-02",
    primaryCompletion: "2031-03",
    status: "Recruiting",
    prevention: "mixed",
    keyDifference: "Oral small-molecule assembly inhibitor. Includes first-event prevention.",
    lpLoweringPct: 85.8,
  },
  {
    id: "precad",
    nctId: "NCT06494501",
    name: "PRECAD",
    agent: "Inclisiran plus aggressive CVRF control",
    sponsor: "Icahn School of Medicine at Mount Sinai",
    company: "Icahn / Mount Sinai",
    mechanism: "PCSK9 siRNA",
    dose: "284 mg SC at predefined time points, for 5 years",
    population:
      "Ages 30–50. No prior CAD, cerebrovascular, or PAD. Subclinical atherosclerosis on 3D vascular ultrasound or CAC ≥25.",
    biomarkerThreshold: "LDL-C >70 mg/dL (1.8 mmol/L) at entry",
    enrollment: 1600,
    enrollmentType: "estimated",
    primaryEndpoint:
      "Change in atherosclerotic plaque burden from baseline at 2.5 years and the last year of follow-up, measured by 3D vascular ultrasound.",
    startDate: "2024-09-12",
    primaryCompletion: "2032-06-30",
    status: "Recruiting",
    prevention: "primary",
    keyDifference:
      "Prevention trial. Experimental arm targets LDL-C <55 mg/dL, BP <130/80, HbA1c <6.5% and includes inclisiran. Control is AHA/ACC usual care. PI Valentin Fuster. Site: Mount Sinai Fuster Heart Hospital.",
    personal: true,
  },
  {
    id: "select",
    nctId: "NCT03574597",
    name: "SELECT",
    agent: "Semaglutide",
    sponsor: "Novo Nordisk A/S",
    company: "Novo Nordisk",
    mechanism: "GLP-1 RA",
    dose: "SC once weekly",
    population:
      "Overweight or obesity. CV death / MI / stroke outcomes. Not a diabetes-treatment trial.",
    biomarkerThreshold: null,
    enrollment: 17604,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time from randomization to first occurrence of a composite of cardiovascular death, non-fatal myocardial infarction, or non-fatal stroke.",
    startDate: "2018-10-24",
    primaryCompletion: "2023-06-21",
    status: "Completed",
    prevention: "mixed",
    keyDifference: "Semaglutide CV outcomes in overweight/obesity without a diabetes indication.",
  },
  {
    id: "surmount-1",
    nctId: "NCT04184622",
    name: "SURMOUNT-1",
    agent: "Tirzepatide",
    sponsor: "Eli Lilly and Company",
    company: "Lilly",
    mechanism: "Dual GIP/GLP-1 RA",
    dose: "SC",
    population:
      "BMI ≥30, or ≥27 with hypertension, dyslipidemia, OSA, or CVD. Weight-loss primary.",
    biomarkerThreshold: null,
    enrollment: 2539,
    enrollmentType: "actual",
    primaryEndpoint:
      "Percent change from baseline in body weight, and percentage of participants who achieve ≥5% body-weight reduction (primary treatment period).",
    startDate: "2019-12-04",
    primaryCompletion: "2022-04-01",
    status: "Completed",
    prevention: "primary",
    keyDifference: "Obesity weight-loss registration trial, not a MACE outcomes study.",
  },
  {
    id: "surmount-2",
    nctId: "NCT04657003",
    name: "SURMOUNT-2",
    agent: "Tirzepatide",
    sponsor: "Eli Lilly and Company",
    company: "Lilly",
    mechanism: "Dual GIP/GLP-1 RA",
    dose: "SC",
    population: "Type 2 diabetes with BMI ≥27. Weight-loss primary.",
    biomarkerThreshold: "HbA1c 7–10% at screening",
    enrollment: 938,
    enrollmentType: "actual",
    primaryEndpoint:
      "Percent change from baseline in body weight, and percentage of participants who achieve ≥5% body-weight reduction (week 72).",
    startDate: "2021-03-29",
    primaryCompletion: "2023-03-16",
    status: "Completed",
    prevention: "primary",
    keyDifference: "Weight-loss trial in type 2 diabetes. Not a MACE outcomes study.",
  },
  {
    id: "flow",
    nctId: "NCT03819153",
    name: "FLOW",
    agent: "Semaglutide",
    sponsor: "Novo Nordisk A/S",
    company: "Novo Nordisk",
    mechanism: "GLP-1 RA",
    dose: "SC once weekly",
    population: "Type 2 diabetes with chronic kidney disease.",
    biomarkerThreshold: "HbA1c ≤10%",
    enrollment: 3533,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time to first persistent ≥50% eGFR reduction, persistent eGFR <15 mL/min/1.73 m², initiation of chronic renal replacement therapy, renal death, or cardiovascular death.",
    startDate: "2019-06-17",
    primaryCompletion: "2024-01-09",
    status: "Completed",
    prevention: "mixed",
    keyDifference: "Kidney-outcomes trial. Composite is renal plus CV death.",
  },
  {
    id: "empa-reg",
    nctId: "NCT01131676",
    name: "EMPA-REG OUTCOME",
    agent: "Empagliflozin",
    sponsor: "Boehringer Ingelheim",
    company: "Boehringer Ingelheim / Lilly",
    mechanism: "SGLT2 inhibitor",
    dose: "Oral once daily (low and high dose)",
    population:
      "Type 2 diabetes on stable background therapy. High CV risk.",
    biomarkerThreshold: "HbA1c 7–10% on background therapy (or ≥7% if drug-naive)",
    enrollment: 7064,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time to first adjudicated 3-point MACE: CV death (including fatal stroke and fatal MI), non-fatal MI (excluding silent MI), or non-fatal stroke.",
    startDate: "2010-07",
    primaryCompletion: "2015-04",
    status: "Completed",
    prevention: "secondary",
    keyDifference: "First SGLT2 inhibitor CVOT to show CV benefit.",
  },
  {
    id: "leader",
    nctId: "NCT01179048",
    name: "LEADER",
    agent: "Liraglutide",
    sponsor: "Novo Nordisk A/S",
    company: "Novo Nordisk",
    mechanism: "GLP-1 RA",
    dose: "Up to 1.8 mg SC once daily",
    population:
      "Type 2 diabetes. Age ≥50 with CV/renal disease, or ≥60 with additional CV risk.",
    biomarkerThreshold: "HbA1c ≥7.0%",
    enrollment: 9341,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time from randomisation to first occurrence of cardiovascular death, non-fatal myocardial infarction, or non-fatal stroke.",
    startDate: "2010-08-31",
    primaryCompletion: "2015-12-17",
    status: "Completed",
    prevention: "mixed",
    keyDifference: "Daily injectable GLP-1 RA CVOT.",
  },
  {
    id: "surpass-cvot",
    nctId: "NCT04255433",
    name: "SURPASS-CVOT",
    agent: "Tirzepatide vs dulaglutide",
    sponsor: "Eli Lilly and Company",
    company: "Lilly",
    mechanism: "Dual GIP/GLP-1 RA",
    dose: "SC",
    population:
      "Age ≥40 with type 2 diabetes and established cardiovascular disease.",
    biomarkerThreshold: null,
    enrollment: 13299,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time to first occurrence of MACE-3: death from cardiovascular causes, myocardial infarction, or stroke.",
    startDate: "2020-05-29",
    primaryCompletion: "2025-06-12",
    status: "Completed",
    prevention: "secondary",
    keyDifference: "Active comparator vs dulaglutide, not placebo.",
  },
  {
    id: "soul",
    nctId: "NCT03914326",
    name: "SOUL",
    agent: "Oral semaglutide",
    sponsor: "Novo Nordisk A/S",
    company: "Novo Nordisk",
    mechanism: "GLP-1 RA",
    dose: "Oral 3 / 7 / 14 mg once daily, fasting",
    population: "Age ≥50 with type 2 diabetes.",
    biomarkerThreshold: "HbA1c 6.5–10.0%",
    enrollment: 9651,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time to first MACE: cardiovascular death, non-fatal myocardial infarction, or non-fatal stroke.",
    startDate: "2019-06-17",
    primaryCompletion: "2024-08-23",
    status: "Completed",
    prevention: "mixed",
    keyDifference: "Oral GLP-1 RA CVOT.",
  },
  {
    id: "clear-outcomes",
    nctId: "NCT02993406",
    name: "CLEAR Outcomes",
    agent: "Bempedoic acid",
    sponsor: "Esperion Therapeutics, Inc.",
    company: "Esperion",
    mechanism: "ACL inhibitor",
    dose: "180 mg oral once daily",
    population:
      "Statin-intolerant adults with, or at high risk for, cardiovascular disease.",
    biomarkerThreshold: null,
    enrollment: 13970,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time to first four-component MACE: death from cardiovascular causes, nonfatal myocardial infarction, nonfatal stroke, or coronary revascularization.",
    startDate: "2016-12-22",
    primaryCompletion: "2022-11-07",
    status: "Completed",
    prevention: "mixed",
    keyDifference: "Oral ACL inhibitor in statin-intolerant patients.",
  },
  {
    id: "fourier",
    nctId: "NCT01764633",
    name: "FOURIER",
    agent: "Evolocumab",
    sponsor: "Amgen",
    company: "Amgen",
    mechanism: "PCSK9 mAb",
    dose: "SC (autoinjector/pen)",
    population:
      "Age 40–85 with clinically evident CVD at high risk for a recurrent event.",
    biomarkerThreshold: "LDL-C ≥70 mg/dL or non-HDL-C ≥100 mg/dL",
    enrollment: 27564,
    enrollmentType: "actual",
    primaryEndpoint:
      "Time to cardiovascular death, myocardial infarction, hospitalization for unstable angina, stroke, or coronary revascularization.",
    startDate: "2013-02-08",
    primaryCompletion: "2016-11-11",
    status: "Completed",
    prevention: "secondary",
    keyDifference: "Large PCSK9 monoclonal antibody outcomes trial.",
  },
];

export function nctUrl(nctId: string): string {
  return `https://clinicaltrials.gov/study/${nctId}`;
}

export function uniqueSponsors(trials: Trial[] = TRIALS): string[] {
  return [...new Set(trials.map((t) => t.sponsor))].sort((a, b) =>
    a.localeCompare(b),
  );
}
